

/*
 * @version:
 * @Author:  StevenJokess https://github.com/StevenJokess
 * @Date: 2020-12-07 20:48:55
 * @LastEditors:  StevenJokess https://github.com/StevenJokess
 * @LastEditTime: 2020-12-07 20:49:06
 * @Description:
 * @TODO::
 * @Reference:https://github.com/cedrickchee/dockerfile-fastai/blob/master/docker_pytorch/Dockerfile
 */
FROM datadrone/deeplearn_opencv

LABEL maintainer="Brian Law <bpl.law@gmail.com>"

RUN conda install -y -c pytorch torchvision
