coverage:
  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes
    patch:
      default:
        enabled: no

https://github.com/lanpa/tensorboardX/blob/master/.codecov.yml
